### ISSUE TITLE
Register and Login pages - cosmetics

### ISSUE THREAD

**Issue by joedavison** [bookmark-org/bookmark#12]
This is about the UI of these pages:

https://bookmark.org/users/register
https://bookmark.org/users/log_in

The style of these forms should be changed to match the style of the "Add archive" form on https://bookmark.org/

That means, no white background, larger input fields, rounded corners etc

**Comment by leobz** [comment]
Duplicated requirement -> https://github.com/bookmark-org/bookmark/issues/66
