### ISSUE TITLE
"Already exists" error message. Save some files of the archive on filesystem but not in DB

### ISSUE THREAD

**Issue by leobz** [bookmark-org/bookmark#32]
On some occasions when I try to add a new archive I receive an "Already exists" message and I can't see the new archive on the page.
Although, I see that some files of the archive it's really saved successfully.

### More info

Already exist message error
![image](https://user-images.githubusercontent.com/43507646/226137142-cb515fec-4c7b-4d7a-8e27-23a77ee701aa.png)

`archivebox add` command output
```
[+] [2023-03-18 20:21:46] Adding 1 links to index (crawl depth=0)...\n    > Saved verbatim input to sources/1679170906-import.txt\n    > Parsed 1 URLs from input (Generic TXT)\n    > Found 0 new URLs not already in index\n\n[*] [2023-03-18 20:21:46] Writing 0 links to main index...\n\r    √ ./index.sqlite3\n
```

archivebox server
![image](https://user-images.githubusercontent.com/43507646/226137793-93e6a01d-dab2-48dc-aabd-6db4fec27055.png)

**Comment by joedavison** [comment]
It's a known bug, the error message itself may also be the a bug. If you manage to debug it please share your findings.

**Comment by leobz** [comment]
Sorry for the delay. I was trying to replicate the error and that was I found:

## Problem

The **problem comes from the archivebox output** because in both cases (Bookmark app and Terminal) the command archive the website, but in the Elixir app, the output given is randomly wrong.

1. Elixir executes the command `archivebox add` 

```
  def archivebox(url) do
    command = "cd #{directory()}; archivebox add #{url}"

    System.cmd("sh", ["-c", command], cd: directory()) <--------
  end

```

2. The command is executed, **the website is archived** (in fact, `System.cmd()` takes a long time to download the files), **but the output** received in Elixir indicates that the file already exists (this output shouldn't allow archive the website, therefore, the problem is that `archivebox` is giving a wrong output)

``` 
[+] [2023-03-18 21:09:04] Adding 1 links to index (crawl depth=0)...
    > Saved verbatim input to sources/1679173744-import.txt
    > Parsed 1 URLs from input (Generic TXT)
    > Found 0 new URLs not already in index <------ This output is wrong.

[*] [2023-03-18 21:09:04] Writing 0 links to main index... 
    √ ./index.sqlite3
```

3. The Elixir app expects this output, but how it is not given from `archivebox`, launch the "Already exists" message:

```
    > Saved verbatim input to sources/1679258473-import.txt
    > Parsed 1 URLs from input (Generic TXT)
    > Found 1 new URLs not already in index     <-----------  Expected output behaviour

[*] [2023-03-19 20:41:13] Writing 1 links to main index...
    √ ./index.sqlite3

[▶] [2023-03-19 20:41:13] Starting archiving of 1 snapshots in index...

[+] [2023-03-19 20:41:14] "bitcoinnews.com/women-bitcoin-adoption"
    https://bitcoinnews.com/women-bitcoin-adoption/
    > ./archive/1679258473.967474              <---------------- Bookmark needs this line to get the identifier
    .....
```

## Posible workaround

I try to change the function `System.cmd` to `System.shell` `:or.cmd`, but I the result was the same....  

Finally, I found the [`IS_TTY` flag](https://github.com/ArchiveBox/ArchiveBox/blob/master/archivebox/config.py#L55) (interactive session) in the archivebox configuration.
Disabling the `isatty` option, ArchiveBox assumes that its output is being redirected to a file or another process and adjusts its output behavior accordingly.

This works for me at the moment (I couldn't replicate the wrong behavior until now).

I'm going to create a pull request if you are okey.

**Comment by joedavison** [comment]
That's really great, thank you so much for debugging that, your PR is very welcome.
