### ISSUE TITLE
Fail to show archive with some webpages

### ISSUE THREAD

**Issue by leobz** [bookmark-org/bookmark#50]
Some webpages, generate archives that fail when you try to see them. (For example http://mercadolibre.com.ar/ or https://github.com/bookmark-org/bookmark/issues/50)

![image](https://github.com/bookmark-org/bookmark/assets/43507646/41c63816-3e90-493f-9066-631f849213e7)

**Comment by joedavison** [comment]
A few notes here: 

1) it should fail gracefully. If the target host 403's our crawler, the whole application should not crash. 

2) we should try to get smart about setting WGET_USER_AGENT

**Comment by leobz** [comment]
Hi @joedavison, yes, I solved that problem with this commit -> https://github.com/bookmark-org/archivebox/commit/42a858a6599872fb6509f28e4917c954af1f312a 
That change fixed for example this page -> https://listado.mercadolibre.com.ar/samsung#D[A:samsung]

In the other hand, I found this error (I put this url `https://github.com/bookmark-org/bookmark/issues/45`) ->
↳ BookmarkWeb.ArchiveController.show/2, at: lib/bookmark_web/controllers/archive_controller.ex:40                                                                                            
url: **"bookmark.org/twitter/46"**
id: "1684954820.066487"
wget_url: nil

So, that bug is caused due the Twitter regex. I'm going to cherry-pick/steal [this commit](https://github.com/bookmark-org/bookmark/pull/54/commits/53748e4ecc07a1058eab221eaddee9a1ae91eab7) from the [Bulk archive PR](https://github.com/bookmark-org/bookmark/pull/54) to fix it.

**Comment by leobz** [comment]
Fixed

- PR -> https://github.com/bookmark-org/bookmark/pull/55
- Already deployed in -> http://146.190.75.127/

![image](https://github.com/bookmark-org/bookmark/assets/43507646/a9522df1-bf4d-4c39-bcd1-bfdd05f6e485)
