### ISSUE TITLE
Bug: .png and .pdf links for an archived .mp4 file cause an error

### ISSUE THREAD

**Issue by joedavison** [bookmark-org/bookmark#79]
http://alpha.bookmark.org/archive/1686854290.752178

**Comment by leobz** [comment]
Good morning. I saw all the DB was cleaned (Probably due to a `make clean` in prod :/ , I have to avoid allowing that option in production).
I restored the previous backup and tried with the same URL.

Seems that the problem was fixed -> https://alpha.bookmark.org/archive/1688304055.204524
