### ISSUE TITLE
Donate button on view archive pages

### ISSUE THREAD

**Issue by joedavison** [bookmark-org/bookmark#80]
<img width="411" alt="Screenshot 2023-06-16 at 1 51 51 PM" src="https://github.com/bookmark-org/bookmark/assets/2687550/836fe3e5-7cdc-465b-8c3f-5492cea8a73c">

Donate in upper right hand of view archive pages currently shows a few different amounts. Instead, this section should show a single button that says "Donate", and it will lead to a dedicated "Donate" page that allows an anonymous or logged in user to donate.

**Comment by joedavison** [comment]
<img width="432" alt="Screenshot 2023-06-16 at 9 26 25 PM" src="https://github.com/bookmark-org/bookmark/assets/2687550/715e3bab-e7b9-45b5-acb6-42bc7e890dbb">

proposed

**Comment by joedavison** [comment]
<img width="436" alt="Screenshot 2023-06-16 at 9 33 19 PM" src="https://github.com/bookmark-org/bookmark/assets/2687550/2fd35135-3e96-46f6-a85d-01f5c6044bf0">

Added ⚡

**Comment by hf5pro** [comment]
I like how Damus has styled their donation window:
![photo_2023-06-15_22-10-56](https://github.com/bookmark-org/bookmark/assets/83848643/608ad110-567c-43f1-a234-061590be9836)


Looks even better in darkmode

**Comment by leobz** [comment]
Great!
